#! /bin/sh
### BEGIN INIT INFO
# Provides:          modem-enable
# Required-Start:    $remote_fs dbus hal
# Required-Stop:     $remote_fs dbus hal
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: network connection manager
# Description:       Daemon for automatically switching network
#                    connections to the best available connection.
### END INIT INFO

set -e

prefix=/usr
exec_prefix=/usr
sbindir=/usr/sbin
localstatedir=/var

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="enable modem by power on/off gpio"
NAME="modem-enable"

DAEMON=${sbindir}/$NAME

PIDDIR=${localstatedir}/run/modem-enable
PIDFILE=$PIDDIR/$NAME.pid

USER=root


#. /lib/lsb/init-functions


#
#       Function that starts the modem.
#
d_start() {
        /usr/sbin/modem_on
        echo "Modem now enabled"
}

#
#       Function that stops the modem.
#
d_stop() {
		/usr/sbin/modem_off
        echo "modem now disabled"
}

#
#       Function that restarts the modem. 
#		A delay is required so not just stop/start
#
d_restart() {
		/usr/sbin/modem_reset
        echo "modem reset"
}


case "$1" in
  start)
        echo "Starting $DESC" "$NAME"
        d_start
        echo $?
        ;;
  stop)
        echo "Stopping $DESC" "$NAME"
        d_stop
        echo $?
        ;;
  restart|force-reload)
        echo "Restarting $DESC" "$NAME"
        d_restart
        echo $?
        ;;
  status)
        echo "status not implemented for modem" 
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
