#!/bin/sh
#this is the GPIO ping for Poer off/on
#POKY
#GPIO=364
#KROGOTH
GPIO=414
SYS=/sys/class/gpio
GPIODIR=$SYS/gpio$GPIO

if [ ! -e $GPIODIR ]
then
    echo $GPIO > $SYS/export
fi

DIR=`cat  $GPIODIR/direction`
if [ $DIR != "out" ]
then
  echo -n out > $GPIODIR/direction
fi
echo 0 > $GPIODIR/value
 
