#!/bin/sh
#
# led_ctrl
# description: Control RTF LED for Aero platform
#

on() {
  echo 1 > /sys/class/gpio/gpio$LED_gpio/value
}

off() {
  echo 0 > /sys/class/gpio/gpio$LED_gpio/value
}

shutdown_seq() {
  for i in $(seq 1 1 5); do
    echo 1 > /sys/class/gpio/gpio$LED_gpio/value
    usleep 50000
    echo 0 > /sys/class/gpio/gpio$LED_gpio/value
    usleep 50000
  done
  echo 1 > /sys/class/gpio/gpio$LED_gpio/value
}

LED_gpio=481
if [ ! -d "/sys/class/gpio/gpio$LED_gpio/" ]; then
  echo $LED_gpio > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio$LED_gpio/direction
fi

case "$1" in
  on)
        on
        ;;
  off)
        off
        ;;
  shutdown_seq)
        shutdown_seq
        ;;
  *)
        echo $"Usage: $0 {on|off|shutdown_seq}"
        exit 1
esac
exit 0
