#! /bin/sh

### BEGIN INIT INFO
# Provides:        Camera Streaming Daemon
# Required-Start:  $network
# Required-Stop:   $network
# Default-Start:   2 3 4 5
# Default-Stop:
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Functions to do individual actions
start() {
	 nohup /usr/bin/csd \
		2>/var/log/csd.log \
		>/dev/null &
}

stop() {
	p=$(pidof csd)
	if [ -n "$p" ]; then
		kill $p
	fi
}

status(){
	ps -ef | grep -m 1 csd
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
	status
	;;
  *)
	echo "Usage: csd { start | stop | status | restart }" >&2
	exit 1
	;;
esac

exit 0
