#!/bin/sh

set +e

ACTION=$2
RECEIVE=$1                

echo "update IPTABLES for $ACTION change: $RECEIVE" 
echo "update IPTABLES for $ACTION change: $RECEIVE" > /dev/console

if [[ $RECEIVE == "wwan0" || $RECEIVE == "wwan1"  || $RECEIVE == "wwan2" || $RECEIVE == "wwan3" ]] ; then
  if [[ $ACTION == "up" ]] ; then
     # create iptables rules
     /usr/bin/setfirewall.sh start $RECEIVE 2>&1 > /dev/console
     echo "Modem now connected - Welcome to Internet" > /dev/console
  elif [[ $ACTION == "down" ]] ; then
     # remove iptables rules
     /usr/bin/setfirewall.sh stop 
  fi
elif  [[ $RECEIVE == "ttyACM0" ]] ; then
  if [[ $ACTION == "down" ]] ; then
     /usr/bin/setfirewall.sh stop 
  fi 
fi

exit


