#! /bin/sh
### BEGIN INIT INFO
# Provides:          NetworkManager
# Required-Start:    $remote_fs dbus hal
# Required-Stop:     $remote_fs dbus hal
# Should-Start:	     $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: network connection manager
# Description:       Daemon for automatically switching network
#		     connections to the best available connection.
### END INIT INFO

set -e

prefix=/usr
exec_prefix=/usr
sbindir=/usr/sbin
localstatedir=/var

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="network connection manager"
NAME="NetworkManager"

DAEMON=${sbindir}/$NAME

PIDDIR=${localstatedir}/run/NetworkManager
PIDFILE=$PIDDIR/$NAME.pid

USER=root

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#. /lib/lsb/init-functions

test -f /etc/default/NetworkManager && . /etc/default/NetworkManager

#
#	Function that starts the daemon/service.
#
d_start() {
	if [ ! -d $PIDDIR ]; then
		mkdir -p $PIDDIR
		chown $USER:$USER $PIDDIR
	fi

        export MM_DEBUG=1
#        ( nohup /usr/sbin/ModemManager ) 2>&1 > /dev/null &
#        sleep 10
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--oknodo --user $USER --exec $DAEMON -- $DAEMON_OPTS --pid-file $PIDFILE

#        sleep 10
#        echo "restart ModemManager" 
#        ps -ef | grep ModemManger
#        kill -9 `ps -ef | grep ModemManager | grep -v grep | cut -c 8-14 `
}

#
#	Function that stops the daemon/service.
#
d_stop() {
	start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE \
		 --oknodo --user $USER --exec $DAEMON
 
}


case "$1" in
  start)
	echo "Starting $DESC" "$NAME"
	d_start
	echo $?
	;;
  stop)
	echo "Stopping $DESC" "$NAME"
	d_stop
	echo $?
	;;
  restart|force-reload)
	echo "Restarting $DESC" "$NAME"
	d_stop
	d_start
	echo $?
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0


